
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    # environment:
    #   TZ: MY_TIME_ZONE
    volumes:
      - ./custom_components:/config/custom_components
    # network_mode: host
    ports:
        - 8123:8123

# docker run -d \
#   --name homeassistant \
#   --privileged \
#   --restart=unless-stopped \
#   -e TZ=MY_TIME_ZONE \
#   -v /PATH_TO_YOUR_CONFIG:/config \
#   -v /run/dbus:/run/dbus:ro \
#   --network=host \
#   ghcr.io/home-assistant/home-assistant:stable